name: CI/CD workflow "Library-Catalogue" - app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x, ]

    steps:
      - name: Checkout program code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install npm pack & Dependencies
        run: npm install
      - name: Install pack
        run: npm install --save-dev mocha
      - name: Install Playwright
        run: npm install -D playwright
      - name: Check and Modify File Permissions
        run: chmod +x tests/ui.test.js
      - name: Test program code with unit tests
        run: npx playwright test tests/ui.test.js
        
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}
    needs: build

