name: CI/CD workflow "Library-Catalogue" - app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, ]

    steps:
    - name: Checkout program code
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install npm pack & Build the program
      run: npm install
    - name: Install pack for test module
      run: npm install -D @playwright/test
    - name: Install pack
      run: npm install --save-dev mocha
    - name: Test program code with unit tests
      run: npx playwright test tests/ui.test.js
